/**
 * 物品配置 - 萌田农场
 * 基于 Moefarm_items_and_recipes.md 详细设计
 */
import type { Season } from "./SeasonConfig";

export enum ItemCategory {
  CROP = 1, // 基础农产品
  PROCESSED = 2, // 加工品
  FOOD = 3, // 食物料理
  BUILDING = 4, // 建筑
  DECORATION = 5, // 装饰品
  SPECIAL = 6, // 特殊物品
  TOOL = 7, // 工具道具
  AD_REWARD = 8, // 广告专属奖励
}

export interface ItemDef {
  id: string;
  name: string;
  category: ItemCategory;
  description: string;
  sellPrice: number;
  buyPrice?: number;
  unlockLevel: number;
  rarity: number; // 1-5星
  iconColor: string;
  isCrop?: boolean;
  cropId?: string;
  growthTime?: number; // 秒
  harvestCount?: number;
  seasons?: Season[];
}

/** 所有物品配置 */
export const ITEM_DB: Record<string, ItemDef> = {
  // ===== 第1类：基础农产品 (A01-A12) =====
  wheat: {
    id: "wheat",
    name: "小麦",
    category: ItemCategory.CROP,
    description: "基础农作物，用于制作面粉",
    sellPrice: 10,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#FFD700",
    harvestCount: 1,
    seasons: ["spring", "autumn"],
  },
  corn: {
    id: "corn",
    name: "玉米",
    category: ItemCategory.CROP,
    description: "甜玉米，合成料理的常用材料",
    sellPrice: 20,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#FFD700",
    harvestCount: 1,
    seasons: ["spring", "summer"],
  },
  tomato: {
    id: "tomato",
    name: "番茄",
    category: ItemCategory.CROP,
    description: "红色蔬菜，营养丰富",
    sellPrice: 15,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#FF4500",
    harvestCount: 2,
    seasons: ["spring", "summer"],
  },
  carrot: {
    id: "carrot",
    name: "胡萝卜",
    category: ItemCategory.CROP,
    description: "橙色蔬菜，清脆爽口",
    sellPrice: 25,
    unlockLevel: 3,
    rarity: 2,
    iconColor: "#FFA500",
    harvestCount: 1,
    seasons: ["spring", "autumn"],
  },
  pumpkin: {
    id: "pumpkin",
    name: "南瓜",
    category: ItemCategory.CROP,
    description: "大南瓜，用于万圣节主题",
    sellPrice: 40,
    unlockLevel: 8,
    rarity: 2,
    iconColor: "#FF8C00",
    harvestCount: 1,
    seasons: ["spring", "summer"],
  },
  strawberry: {
    id: "strawberry",
    name: "草莓",
    category: ItemCategory.CROP,
    description: "红色果实，制作果酱",
    sellPrice: 30,
    unlockLevel: 12,
    rarity: 3,
    iconColor: "#FF1493",
    harvestCount: 2,
    seasons: ["spring", "autumn"],
  },
  cherry: {
    id: "cherry",
    name: "樱桃",
    category: ItemCategory.CROP,
    description: "珍贵果实，特殊配方用",
    sellPrice: 35,
    unlockLevel: 16,
    rarity: 3,
    iconColor: "#DC143C",
    harvestCount: 3,
    seasons: ["spring", "autumn"],
  },
  banana: {
    id: "banana",
    name: "香蕉",
    category: ItemCategory.CROP,
    description: "黄色水果，营养丰富",
    sellPrice: 22,
    unlockLevel: 10,
    rarity: 2,
    iconColor: "#FFD700",
    harvestCount: 1,
    seasons: ["spring", "summer"],
  },
  apple: {
    id: "apple",
    name: "苹果",
    category: ItemCategory.CROP,
    description: "红色水果，多用途",
    sellPrice: 28,
    unlockLevel: 14,
    rarity: 3,
    iconColor: "#FF4500",
    harvestCount: 1,
    seasons: ["spring", "autumn"],
  },
  lettuce: {
    id: "lettuce",
    name: "莴笋",
    category: ItemCategory.CROP,
    description: "茎肉脆嫩的春秋蔬菜",
    sellPrice: 18,
    unlockLevel: 5,
    rarity: 2,
    iconColor: "#90EE90",
    harvestCount: 2,
    seasons: ["spring", "autumn", "winter"],
  },
  potato: {
    id: "potato",
    name: "马铃薯",
    category: ItemCategory.CROP,
    description: "块茎作物，口感绵软",
    sellPrice: 16,
    unlockLevel: 2,
    rarity: 1,
    iconColor: "#C78B45",
    harvestCount: 2,
    seasons: ["spring", "autumn"],
  },
  cucumber: {
    id: "cucumber",
    name: "黄瓜",
    category: ItemCategory.CROP,
    description: "清爽脆嫩的夏季瓜果",
    sellPrice: 20,
    unlockLevel: 4,
    rarity: 2,
    iconColor: "#63A844",
    harvestCount: 2,
    seasons: ["spring", "summer"],
  },
  sweetPotato: {
    id: "sweetPotato",
    name: "甘薯",
    category: ItemCategory.CROP,
    description: "香甜耐储的块根作物",
    sellPrice: 26,
    unlockLevel: 7,
    rarity: 2,
    iconColor: "#B85C45",
    harvestCount: 2,
    seasons: ["spring", "summer"],
  },
  spinach: {
    id: "spinach",
    name: "菠菜",
    category: ItemCategory.CROP,
    description: "耐寒的深绿叶菜",
    sellPrice: 19,
    unlockLevel: 6,
    rarity: 2,
    iconColor: "#4F9B4A",
    harvestCount: 2,
    seasons: ["spring", "autumn", "winter"],
  },
  pea: {
    id: "pea",
    name: "豌豆",
    category: ItemCategory.CROP,
    description: "春季结荚的清甜豆类",
    sellPrice: 18,
    unlockLevel: 2,
    rarity: 1,
    iconColor: "#79B83E",
    harvestCount: 3,
    seasons: ["spring", "autumn"],
  },
  asparagus: {
    id: "asparagus",
    name: "芦笋",
    category: ItemCategory.CROP,
    description: "鲜嫩挺拔的春季嫩茎",
    sellPrice: 26,
    unlockLevel: 4,
    rarity: 2,
    iconColor: "#79A94A",
    harvestCount: 2,
    seasons: ["spring"],
  },
  rhubarb: {
    id: "rhubarb",
    name: "大黄",
    category: ItemCategory.CROP,
    description: "红茎宽叶的春季作物",
    sellPrice: 30,
    unlockLevel: 6,
    rarity: 2,
    iconColor: "#C34D5B",
    harvestCount: 2,
    seasons: ["spring"],
  },
  fennel: {
    id: "fennel",
    name: "茴香",
    category: ItemCategory.CROP,
    description: "清香脆嫩的球茎蔬菜",
    sellPrice: 24,
    unlockLevel: 7,
    rarity: 2,
    iconColor: "#A8C96A",
    harvestCount: 2,
    seasons: ["spring", "autumn"],
  },
  artichoke: {
    id: "artichoke",
    name: "洋蓟",
    category: ItemCategory.CROP,
    description: "层叠饱满的春季花苞",
    sellPrice: 38,
    unlockLevel: 9,
    rarity: 3,
    iconColor: "#789D58",
    harvestCount: 1,
    seasons: ["spring", "autumn"],
  },
  eggplant: {
    id: "eggplant",
    name: "茄子",
    category: ItemCategory.CROP,
    description: "油亮饱满的夏季紫茄",
    sellPrice: 28,
    unlockLevel: 5,
    rarity: 2,
    iconColor: "#79539A",
    harvestCount: 2,
    seasons: ["spring", "summer"],
  },
  sweetPepper: {
    id: "sweetPepper",
    name: "甜椒",
    category: ItemCategory.CROP,
    description: "色彩明快的夏季甜椒",
    sellPrice: 30,
    unlockLevel: 7,
    rarity: 2,
    iconColor: "#E84A3C",
    harvestCount: 2,
    seasons: ["spring", "summer"],
  },
  watermelon: {
    id: "watermelon",
    name: "西瓜",
    category: ItemCategory.CROP,
    description: "清甜多汁的夏季西瓜",
    sellPrice: 42,
    unlockLevel: 9,
    rarity: 3,
    iconColor: "#3E9A4A",
    harvestCount: 1,
    seasons: ["spring", "summer"],
  },
  okra: {
    id: "okra",
    name: "秋葵",
    category: ItemCategory.CROP,
    description: "脆嫩修长的夏季秋葵",
    sellPrice: 32,
    unlockLevel: 11,
    rarity: 2,
    iconColor: "#65A844",
    harvestCount: 2,
    seasons: ["spring", "summer"],
  },
  peanut: {
    id: "peanut",
    name: "花生",
    category: ItemCategory.CROP,
    description: "香脆饱满的夏季花生",
    sellPrice: 36,
    unlockLevel: 13,
    rarity: 2,
    iconColor: "#D6A85A",
    harvestCount: 2,
    seasons: ["spring", "summer"],
  },
  broccoli: {
    id: "broccoli",
    name: "西兰花",
    category: ItemCategory.CROP,
    description: "花球紧实的秋季十字花科蔬菜",
    sellPrice: 32,
    unlockLevel: 15,
    rarity: 2,
    iconColor: "#63A844",
    harvestCount: 2,
    seasons: ["spring", "autumn"],
  },
  beetroot: {
    id: "beetroot",
    name: "甜菜根",
    category: ItemCategory.CROP,
    description: "紫红圆润的秋季根菜",
    sellPrice: 28,
    unlockLevel: 16,
    rarity: 2,
    iconColor: "#A92D4B",
    harvestCount: 2,
    seasons: ["spring", "autumn"],
  },
  turnip: {
    id: "turnip",
    name: "芜菁",
    category: ItemCategory.CROP,
    description: "紫肩白根的清甜秋季根菜",
    sellPrice: 26,
    unlockLevel: 17,
    rarity: 2,
    iconColor: "#B36BB5",
    harvestCount: 2,
    seasons: ["spring", "autumn"],
  },
  celery: {
    id: "celery",
    name: "芹菜",
    category: ItemCategory.CROP,
    description: "叶柄清脆的秋季蔬菜",
    sellPrice: 30,
    unlockLevel: 18,
    rarity: 2,
    iconColor: "#A6C957",
    harvestCount: 2,
    seasons: ["spring", "autumn"],
  },
  ginger: {
    id: "ginger",
    name: "生姜",
    category: ItemCategory.CROP,
    description: "辛香饱满的秋季根茎作物",
    sellPrice: 38,
    unlockLevel: 19,
    rarity: 3,
    iconColor: "#D9A84E",
    harvestCount: 2,
    seasons: ["spring", "summer"],
  },
  kale: {
    id: "kale",
    name: "羽衣甘蓝",
    category: ItemCategory.CROP,
    description: "卷叶舒展的耐寒冬季叶菜",
    sellPrice: 30,
    unlockLevel: 20,
    rarity: 2,
    iconColor: "#6FA943",
    harvestCount: 2,
    seasons: ["spring", "autumn", "winter"],
  },
  chineseCabbage: {
    id: "chineseCabbage",
    name: "大白菜",
    category: ItemCategory.CROP,
    description: "叶球紧实的冬季大白菜",
    sellPrice: 34,
    unlockLevel: 21,
    rarity: 2,
    iconColor: "#C5D969",
    harvestCount: 2,
    seasons: ["autumn", "winter"],
  },
  garlic: {
    id: "garlic",
    name: "大蒜",
    category: ItemCategory.CROP,
    description: "蒜瓣饱满的耐寒鳞茎作物",
    sellPrice: 36,
    unlockLevel: 22,
    rarity: 2,
    iconColor: "#F2E4B8",
    harvestCount: 2,
    seasons: ["autumn", "winter"],
  },
  leek: {
    id: "leek",
    name: "韭葱",
    category: ItemCategory.CROP,
    description: "葱白粗长的冬季葱属蔬菜",
    sellPrice: 32,
    unlockLevel: 23,
    rarity: 2,
    iconColor: "#74A879",
    harvestCount: 2,
    seasons: ["spring", "autumn", "winter"],
  },
  brusselsSprouts: {
    id: "brusselsSprouts",
    name: "小卷心菜",
    category: ItemCategory.CROP,
    description: "茎生球芽累累的冬季蔬菜",
    sellPrice: 42,
    unlockLevel: 24,
    rarity: 3,
    iconColor: "#72A944",
    harvestCount: 3,
    seasons: ["spring", "autumn"],
  },

  // 种植只消耗种子袋，收获后得到上方对应的成熟农作物。
  seedWheat: {
    id: "seedWheat",
    name: "小麦种子",
    category: ItemCategory.CROP,
    description: "可种植小麦",
    sellPrice: 4,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#FFD700",
    isCrop: true,
    cropId: "wheat",
    growthTime: 30,
    seasons: ["spring", "autumn"],
  },
  seedCorn: {
    id: "seedCorn",
    name: "玉米种子",
    category: ItemCategory.CROP,
    description: "可种植玉米",
    sellPrice: 7,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#FFD700",
    isCrop: true,
    cropId: "corn",
    growthTime: 60,
    seasons: ["spring", "summer"],
  },
  seedTomato: {
    id: "seedTomato",
    name: "番茄种子",
    category: ItemCategory.CROP,
    description: "可种植番茄",
    sellPrice: 5,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#FF4500",
    isCrop: true,
    cropId: "tomato",
    growthTime: 90,
    seasons: ["spring", "summer"],
  },
  seedCarrot: {
    id: "seedCarrot",
    name: "胡萝卜种子",
    category: ItemCategory.CROP,
    description: "可种植胡萝卜",
    sellPrice: 8,
    unlockLevel: 3,
    rarity: 2,
    iconColor: "#FFA500",
    isCrop: true,
    cropId: "carrot",
    growthTime: 120,
    seasons: ["spring", "autumn"],
  },
  seedLettuce: {
    id: "seedLettuce",
    name: "莴笋种子",
    category: ItemCategory.CROP,
    description: "可种植莴笋",
    sellPrice: 6,
    unlockLevel: 5,
    rarity: 2,
    iconColor: "#90EE90",
    isCrop: true,
    cropId: "lettuce",
    growthTime: 75,
    seasons: ["spring", "autumn", "winter"],
  },
  seedPumpkin: {
    id: "seedPumpkin",
    name: "南瓜种子",
    category: ItemCategory.CROP,
    description: "可种植南瓜",
    sellPrice: 12,
    unlockLevel: 8,
    rarity: 2,
    iconColor: "#FF8C00",
    isCrop: true,
    cropId: "pumpkin",
    growthTime: 180,
    seasons: ["spring", "summer"],
  },
  seedBanana: {
    id: "seedBanana",
    name: "香蕉种子",
    category: ItemCategory.CROP,
    description: "可种植香蕉",
    sellPrice: 7,
    unlockLevel: 10,
    rarity: 2,
    iconColor: "#FFD700",
    isCrop: true,
    cropId: "banana",
    growthTime: 100,
    seasons: ["spring", "summer"],
  },
  seedStrawberry: {
    id: "seedStrawberry",
    name: "草莓种子",
    category: ItemCategory.CROP,
    description: "可种植草莓",
    sellPrice: 9,
    unlockLevel: 12,
    rarity: 3,
    iconColor: "#FF1493",
    isCrop: true,
    cropId: "strawberry",
    growthTime: 120,
    seasons: ["spring", "autumn"],
  },
  seedApple: {
    id: "seedApple",
    name: "苹果种子",
    category: ItemCategory.CROP,
    description: "可种植苹果",
    sellPrice: 9,
    unlockLevel: 14,
    rarity: 3,
    iconColor: "#FF4500",
    isCrop: true,
    cropId: "apple",
    growthTime: 140,
    seasons: ["spring", "autumn"],
  },
  seedCherry: {
    id: "seedCherry",
    name: "樱桃种子",
    category: ItemCategory.CROP,
    description: "可种植樱桃",
    sellPrice: 11,
    unlockLevel: 16,
    rarity: 3,
    iconColor: "#DC143C",
    isCrop: true,
    cropId: "cherry",
    growthTime: 150,
    seasons: ["spring", "autumn"],
  },
  seedPotato: {
    id: "seedPotato",
    name: "马铃薯种薯",
    category: ItemCategory.CROP,
    description: "可种植马铃薯",
    sellPrice: 6,
    unlockLevel: 2,
    rarity: 1,
    iconColor: "#C78B45",
    isCrop: true,
    cropId: "potato",
    growthTime: 70,
    seasons: ["spring", "autumn"],
  },
  seedCucumber: {
    id: "seedCucumber",
    name: "黄瓜种子",
    category: ItemCategory.CROP,
    description: "可种植黄瓜",
    sellPrice: 7,
    unlockLevel: 4,
    rarity: 2,
    iconColor: "#63A844",
    isCrop: true,
    cropId: "cucumber",
    growthTime: 85,
    seasons: ["spring", "summer"],
  },
  seedSweetPotato: {
    id: "seedSweetPotato",
    name: "甘薯种薯",
    category: ItemCategory.CROP,
    description: "可种植甘薯",
    sellPrice: 9,
    unlockLevel: 7,
    rarity: 2,
    iconColor: "#B85C45",
    isCrop: true,
    cropId: "sweetPotato",
    growthTime: 110,
    seasons: ["spring", "summer"],
  },
  seedSpinach: {
    id: "seedSpinach",
    name: "菠菜种子",
    category: ItemCategory.CROP,
    description: "可种植菠菜",
    sellPrice: 7,
    unlockLevel: 6,
    rarity: 2,
    iconColor: "#4F9B4A",
    isCrop: true,
    cropId: "spinach",
    growthTime: 80,
    seasons: ["spring", "autumn", "winter"],
  },
  seedPea: {
    id: "seedPea",
    name: "豌豆种子",
    category: ItemCategory.CROP,
    description: "可种植豌豆",
    sellPrice: 6,
    unlockLevel: 2,
    rarity: 1,
    iconColor: "#79B83E",
    isCrop: true,
    cropId: "pea",
    growthTime: 70,
    seasons: ["spring", "autumn"],
  },
  seedAsparagus: {
    id: "seedAsparagus",
    name: "芦笋种子",
    category: ItemCategory.CROP,
    description: "可种植芦笋",
    sellPrice: 9,
    unlockLevel: 4,
    rarity: 2,
    iconColor: "#79A94A",
    isCrop: true,
    cropId: "asparagus",
    growthTime: 95,
    seasons: ["spring"],
  },
  seedRhubarb: {
    id: "seedRhubarb",
    name: "大黄种子",
    category: ItemCategory.CROP,
    description: "可种植大黄",
    sellPrice: 10,
    unlockLevel: 6,
    rarity: 2,
    iconColor: "#C34D5B",
    isCrop: true,
    cropId: "rhubarb",
    growthTime: 105,
    seasons: ["spring"],
  },
  seedFennel: {
    id: "seedFennel",
    name: "茴香种子",
    category: ItemCategory.CROP,
    description: "可种植茴香",
    sellPrice: 8,
    unlockLevel: 7,
    rarity: 2,
    iconColor: "#A8C96A",
    isCrop: true,
    cropId: "fennel",
    growthTime: 90,
    seasons: ["spring", "autumn"],
  },
  seedArtichoke: {
    id: "seedArtichoke",
    name: "洋蓟种子",
    category: ItemCategory.CROP,
    description: "可种植洋蓟",
    sellPrice: 12,
    unlockLevel: 9,
    rarity: 3,
    iconColor: "#789D58",
    isCrop: true,
    cropId: "artichoke",
    growthTime: 135,
    seasons: ["spring", "autumn"],
  },
  seedEggplant: {
    id: "seedEggplant",
    name: "茄子种子",
    category: ItemCategory.CROP,
    description: "可种植茄子",
    sellPrice: 9,
    unlockLevel: 5,
    rarity: 2,
    iconColor: "#79539A",
    isCrop: true,
    cropId: "eggplant",
    growthTime: 100,
    seasons: ["spring", "summer"],
  },
  seedSweetPepper: {
    id: "seedSweetPepper",
    name: "甜椒种子",
    category: ItemCategory.CROP,
    description: "可种植甜椒",
    sellPrice: 10,
    unlockLevel: 7,
    rarity: 2,
    iconColor: "#E84A3C",
    isCrop: true,
    cropId: "sweetPepper",
    growthTime: 110,
    seasons: ["spring", "summer"],
  },
  seedWatermelon: {
    id: "seedWatermelon",
    name: "西瓜种子",
    category: ItemCategory.CROP,
    description: "可种植西瓜",
    sellPrice: 14,
    unlockLevel: 9,
    rarity: 3,
    iconColor: "#3E9A4A",
    isCrop: true,
    cropId: "watermelon",
    growthTime: 150,
    seasons: ["spring", "summer"],
  },
  seedOkra: {
    id: "seedOkra",
    name: "秋葵种子",
    category: ItemCategory.CROP,
    description: "可种植秋葵",
    sellPrice: 11,
    unlockLevel: 11,
    rarity: 2,
    iconColor: "#65A844",
    isCrop: true,
    cropId: "okra",
    growthTime: 120,
    seasons: ["spring", "summer"],
  },
  seedPeanut: {
    id: "seedPeanut",
    name: "花生种子",
    category: ItemCategory.CROP,
    description: "可种植花生",
    sellPrice: 12,
    unlockLevel: 13,
    rarity: 2,
    iconColor: "#D6A85A",
    isCrop: true,
    cropId: "peanut",
    growthTime: 140,
    seasons: ["spring", "summer"],
  },
  seedBroccoli: {
    id: "seedBroccoli",
    name: "西兰花种子",
    category: ItemCategory.CROP,
    description: "可种植西兰花",
    sellPrice: 11,
    unlockLevel: 15,
    rarity: 2,
    iconColor: "#63A844",
    isCrop: true,
    cropId: "broccoli",
    growthTime: 120,
    seasons: ["spring", "autumn"],
  },
  seedBeetroot: {
    id: "seedBeetroot",
    name: "甜菜根种子",
    category: ItemCategory.CROP,
    description: "可种植甜菜根",
    sellPrice: 10,
    unlockLevel: 16,
    rarity: 2,
    iconColor: "#A92D4B",
    isCrop: true,
    cropId: "beetroot",
    growthTime: 100,
    seasons: ["spring", "autumn"],
  },
  seedTurnip: {
    id: "seedTurnip",
    name: "芜菁种子",
    category: ItemCategory.CROP,
    description: "可种植芜菁",
    sellPrice: 9,
    unlockLevel: 17,
    rarity: 2,
    iconColor: "#B36BB5",
    isCrop: true,
    cropId: "turnip",
    growthTime: 95,
    seasons: ["spring", "autumn"],
  },
  seedCelery: {
    id: "seedCelery",
    name: "芹菜种子",
    category: ItemCategory.CROP,
    description: "可种植芹菜",
    sellPrice: 10,
    unlockLevel: 18,
    rarity: 2,
    iconColor: "#A6C957",
    isCrop: true,
    cropId: "celery",
    growthTime: 110,
    seasons: ["spring", "autumn"],
  },
  seedGinger: {
    id: "seedGinger",
    name: "生姜种子",
    category: ItemCategory.CROP,
    description: "可种植生姜",
    sellPrice: 13,
    unlockLevel: 19,
    rarity: 3,
    iconColor: "#D9A84E",
    isCrop: true,
    cropId: "ginger",
    growthTime: 140,
    seasons: ["spring", "summer"],
  },
  seedKale: {
    id: "seedKale",
    name: "羽衣甘蓝种子",
    category: ItemCategory.CROP,
    description: "可种植羽衣甘蓝",
    sellPrice: 10,
    unlockLevel: 20,
    rarity: 2,
    iconColor: "#6FA943",
    isCrop: true,
    cropId: "kale",
    growthTime: 110,
    seasons: ["spring", "autumn", "winter"],
  },
  seedChineseCabbage: {
    id: "seedChineseCabbage",
    name: "大白菜种子",
    category: ItemCategory.CROP,
    description: "可种植大白菜",
    sellPrice: 11,
    unlockLevel: 21,
    rarity: 2,
    iconColor: "#C5D969",
    isCrop: true,
    cropId: "chineseCabbage",
    growthTime: 125,
    seasons: ["autumn", "winter"],
  },
  seedGarlic: {
    id: "seedGarlic",
    name: "大蒜种子",
    category: ItemCategory.CROP,
    description: "可种植大蒜",
    sellPrice: 12,
    unlockLevel: 22,
    rarity: 2,
    iconColor: "#F2E4B8",
    isCrop: true,
    cropId: "garlic",
    growthTime: 130,
    seasons: ["autumn", "winter"],
  },
  seedLeek: {
    id: "seedLeek",
    name: "韭葱种子",
    category: ItemCategory.CROP,
    description: "可种植韭葱",
    sellPrice: 11,
    unlockLevel: 23,
    rarity: 2,
    iconColor: "#74A879",
    isCrop: true,
    cropId: "leek",
    growthTime: 120,
    seasons: ["spring", "autumn", "winter"],
  },
  seedBrusselsSprouts: {
    id: "seedBrusselsSprouts",
    name: "小卷心菜种子",
    category: ItemCategory.CROP,
    description: "可种植小卷心菜",
    sellPrice: 14,
    unlockLevel: 24,
    rarity: 3,
    iconColor: "#72A944",
    isCrop: true,
    cropId: "brusselsSprouts",
    growthTime: 150,
    seasons: ["spring", "autumn"],
  },

  egg: {
    id: "egg",
    name: "鸡蛋",
    category: ItemCategory.PROCESSED,
    description: "养鸡场产出，烘焙必需",
    sellPrice: 25,
    unlockLevel: 6,
    rarity: 2,
    iconColor: "#FFD700",
  },
  milk: {
    id: "milk",
    name: "牛奶",
    category: ItemCategory.PROCESSED,
    description: "牧场产出，烹饪常用",
    sellPrice: 24,
    unlockLevel: 7,
    rarity: 2,
    iconColor: "#FFFFFF",
  },

  // ===== 第2类：加工品 (B01-B10) =====
  flour: {
    id: "flour",
    name: "面粉",
    category: ItemCategory.PROCESSED,
    description: "小麦研磨而成，烘焙基础",
    sellPrice: 25,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#F5F5DC",
  },
  butter: {
    id: "butter",
    name: "黄油",
    category: ItemCategory.PROCESSED,
    description: "牛奶加工而成，增加香味",
    sellPrice: 30,
    unlockLevel: 7,
    rarity: 1,
    iconColor: "#FFD700",
  },
  honey: {
    id: "honey",
    name: "蜂蜜",
    category: ItemCategory.PROCESSED,
    description: "蜜蜂采集，甜味调料",
    sellPrice: 35,
    unlockLevel: 10,
    rarity: 2,
    iconColor: "#DAA520",
  },
  sugar: {
    id: "sugar",
    name: "糖",
    category: ItemCategory.PROCESSED,
    description: "甘蔗加工，甜味基础",
    sellPrice: 28,
    unlockLevel: 5,
    rarity: 1,
    iconColor: "#FFFFFF",
  },
  oatmeal: {
    id: "oatmeal",
    name: "燕麦",
    category: ItemCategory.PROCESSED,
    description: "燕麦谷物，健康食材",
    sellPrice: 22,
    unlockLevel: 8,
    rarity: 1,
    iconColor: "#D2B48C",
  },
  bananaSauce: {
    id: "bananaSauce",
    name: "香甜香蕉酱",
    category: ItemCategory.PROCESSED,
    description: "成熟香蕉慢熬制成的香甜果酱",
    sellPrice: 85,
    unlockLevel: 12,
    rarity: 3,
    iconColor: "#FFD700",
  },
  cherryJam: {
    id: "cherryJam",
    name: "樱桃果酱瓶",
    category: ItemCategory.PROCESSED,
    description: "樱桃与糖慢熬制成的红润果酱",
    sellPrice: 105,
    unlockLevel: 16,
    rarity: 4,
    iconColor: "#C2183B",
  },
  jam: {
    id: "jam",
    name: "果酱",
    category: ItemCategory.PROCESSED,
    description: "草莓/樱桃加工，涂抹食材",
    sellPrice: 42,
    unlockLevel: 14,
    rarity: 3,
    iconColor: "#DC143C",
  },
  carrotPuree: {
    id: "carrotPuree",
    name: "胡萝卜泥",
    category: ItemCategory.PROCESSED,
    description: "胡萝卜研磨，辅助食材",
    sellPrice: 32,
    unlockLevel: 4,
    rarity: 2,
    iconColor: "#FFA500",
  },
  cheese: {
    id: "cheese",
    name: "奶酪",
    category: ItemCategory.PROCESSED,
    description: "牛奶发酵，风味食材",
    sellPrice: 40,
    unlockLevel: 11,
    rarity: 3,
    iconColor: "#FFFACD",
  },
  ketchup: {
    id: "ketchup",
    name: "番茄酱",
    category: ItemCategory.PROCESSED,
    description: "番茄加工，调味料",
    sellPrice: 35,
    unlockLevel: 3,
    rarity: 2,
    iconColor: "#DC143C",
  },
  water: {
    id: "water",
    name: "清水",
    category: ItemCategory.PROCESSED,
    description: "水井产出的清水，可用于高级加工",
    sellPrice: 18,
    unlockLevel: 13,
    rarity: 2,
    iconColor: "#87CEEB",
  },

  // ===== 第3类：食物料理 (C01-C15) =====
  bread: {
    id: "bread",
    name: "面包",
    category: ItemCategory.FOOD,
    description: "面粉烤制，基础食物",
    sellPrice: 60,
    unlockLevel: 5,
    rarity: 2,
    iconColor: "#8B4513",
  },
  croissant: {
    id: "croissant",
    name: "牛角面包",
    category: ItemCategory.FOOD,
    description: "黄油烤制，精致早餐",
    sellPrice: 75,
    unlockLevel: 9,
    rarity: 3,
    iconColor: "#D2691E",
  },
  cake: {
    id: "cake",
    name: "蛋糕",
    category: ItemCategory.FOOD,
    description: "鸡蛋烤制，甜蜜点心",
    sellPrice: 85,
    unlockLevel: 12,
    rarity: 3,
    iconColor: "#FFB6C1",
  },
  cupcake: {
    id: "cupcake",
    name: "纸杯蛋糕",
    category: ItemCategory.FOOD,
    description: "个性小蛋糕，可爱造型",
    sellPrice: 70,
    unlockLevel: 12,
    rarity: 3,
    iconColor: "#FFB6C1",
  },
  cookie: {
    id: "cookie",
    name: "饼干",
    category: ItemCategory.FOOD,
    description: "黄油烤制，香脆点心",
    sellPrice: 65,
    unlockLevel: 9,
    rarity: 2,
    iconColor: "#8B4513",
  },
  pie: {
    id: "pie",
    name: "派",
    category: ItemCategory.FOOD,
    description: "水果派，经典甜点",
    sellPrice: 80,
    unlockLevel: 14,
    rarity: 4,
    iconColor: "#DAA520",
  },
  strawberryCake: {
    id: "strawberryCake",
    name: "草莓蛋糕",
    category: ItemCategory.FOOD,
    description: "草莓装饰，豪华甜点",
    sellPrice: 95,
    unlockLevel: 18,
    rarity: 4,
    iconColor: "#FF1493",
  },
  baguette: {
    id: "baguette",
    name: "法棍面包",
    category: ItemCategory.FOOD,
    description: "脆皮法包，经典款",
    sellPrice: 70,
    unlockLevel: 15,
    rarity: 3,
    iconColor: "#8B4513",
  },
  donut: {
    id: "donut",
    name: "甜甜圈",
    category: ItemCategory.FOOD,
    description: "油炸甜点，童年味道",
    sellPrice: 65,
    unlockLevel: 11,
    rarity: 3,
    iconColor: "#FFB6C1",
  },
  chocolateCake: {
    id: "chocolateCake",
    name: "巧克力蛋糕",
    category: ItemCategory.FOOD,
    description: "巧克力烤制，顶级甜点",
    sellPrice: 100,
    unlockLevel: 22,
    rarity: 5,
    iconColor: "#3E2723",
  },
  cornFlakes: {
    id: "cornFlakes",
    name: "玉米片",
    category: ItemCategory.FOOD,
    description: "玉米加工成的香脆食品",
    sellPrice: 48,
    unlockLevel: 3,
    rarity: 2,
    iconColor: "#E6B84B",
  },
  cereal: {
    id: "cereal",
    name: "麦片",
    category: ItemCategory.FOOD,
    description: "燕麦早餐，健康食品",
    sellPrice: 55,
    unlockLevel: 8,
    rarity: 2,
    iconColor: "#D2B48C",
  },
  pasta: {
    id: "pasta",
    name: "意面",
    category: ItemCategory.FOOD,
    description: "小麦制品，经典意菜",
    sellPrice: 70,
    unlockLevel: 8,
    rarity: 3,
    iconColor: "#DAA520",
  },
  butterToast: {
    id: "butterToast",
    name: "黄油吐司",
    category: ItemCategory.FOOD,
    description: "吐司涂黄油，快手早餐",
    sellPrice: 60,
    unlockLevel: 10,
    rarity: 2,
    iconColor: "#8B4513",
  },
  honeyToast: {
    id: "honeyToast",
    name: "蜂蜜吐司",
    category: ItemCategory.FOOD,
    description: "吐司淋蜂蜜，香甜早餐",
    sellPrice: 65,
    unlockLevel: 13,
    rarity: 2,
    iconColor: "#DAA520",
  },
  jamToast: {
    id: "jamToast",
    name: "果酱吐司",
    category: ItemCategory.FOOD,
    description: "吐司涂果酱，鲜美早餐",
    sellPrice: 62,
    unlockLevel: 16,
    rarity: 2,
    iconColor: "#DC143C",
  },
  applePie: {
    id: "applePie",
    name: "香甜苹果派",
    category: ItemCategory.FOOD,
    description: "苹果切片与黄油烘焙的香甜果派",
    sellPrice: 115,
    unlockLevel: 14,
    rarity: 4,
    iconColor: "#D9892B",
  },
  watermelonJuice: {
    id: "watermelonJuice",
    name: "冰爽西瓜汁",
    category: ItemCategory.FOOD,
    description: "成熟西瓜榨制的清甜冰爽果汁",
    sellPrice: 110,
    unlockLevel: 12,
    rarity: 4,
    iconColor: "#F05C55",
  },
  broccoliCheeseSoup: {
    id: "broccoliCheeseSoup",
    name: "奶酪西兰花汤",
    category: ItemCategory.FOOD,
    description: "西兰花与奶酪熬制的香浓汤品",
    sellPrice: 125,
    unlockLevel: 15,
    rarity: 3,
    iconColor: "#8BC34A",
  },
  beetrootSalad: {
    id: "beetrootSalad",
    name: "甜菜根沙拉",
    category: ItemCategory.FOOD,
    description: "甜菜根与胡萝卜制作的清爽沙拉",
    sellPrice: 110,
    unlockLevel: 16,
    rarity: 3,
    iconColor: "#C2185B",
  },
  turnipSoup: {
    id: "turnipSoup",
    name: "香浓芜菁汤",
    category: ItemCategory.FOOD,
    description: "芜菁与牛奶熬制的柔滑浓汤",
    sellPrice: 115,
    unlockLevel: 17,
    rarity: 3,
    iconColor: "#CE93D8",
  },
  celeryJuice: {
    id: "celeryJuice",
    name: "鲜榨芹菜汁",
    category: ItemCategory.FOOD,
    description: "新鲜芹菜榨制的清爽蔬菜汁",
    sellPrice: 105,
    unlockLevel: 18,
    rarity: 3,
    iconColor: "#9CCC65",
  },
  gingerTea: {
    id: "gingerTea",
    name: "暖香蜂蜜姜茶",
    category: ItemCategory.FOOD,
    description: "生姜与蜂蜜冲泡的暖香茶饮",
    sellPrice: 120,
    unlockLevel: 19,
    rarity: 3,
    iconColor: "#E9A23B",
  },
  kaleSalad: {
    id: "kaleSalad",
    name: "羽衣甘蓝沙拉",
    category: ItemCategory.FOOD,
    description: "羽衣甘蓝、番茄与奶酪制作的沙拉",
    sellPrice: 130,
    unlockLevel: 20,
    rarity: 4,
    iconColor: "#558B2F",
  },
  cabbageRoll: {
    id: "cabbageRoll",
    name: "田园白菜卷",
    category: ItemCategory.FOOD,
    description: "大白菜叶包裹蔬菜馅制成的菜卷",
    sellPrice: 140,
    unlockLevel: 21,
    rarity: 4,
    iconColor: "#D4E157",
  },
  garlicBread: {
    id: "garlicBread",
    name: "黄油蒜香面包",
    category: ItemCategory.FOOD,
    description: "蒜蓉黄油烤制的香脆面包",
    sellPrice: 145,
    unlockLevel: 22,
    rarity: 4,
    iconColor: "#F4B942",
  },
  leekSoup: {
    id: "leekSoup",
    name: "韭葱土豆浓汤",
    category: ItemCategory.FOOD,
    description: "韭葱与土豆熬制的温润浓汤",
    sellPrice: 155,
    unlockLevel: 23,
    rarity: 4,
    iconColor: "#A8C95A",
  },
  roastedBrusselsSprouts: {
    id: "roastedBrusselsSprouts",
    name: "黄油小卷心",
    category: ItemCategory.FOOD,
    description: "小卷心菜搭配黄油烤制的高级料理",
    sellPrice: 165,
    unlockLevel: 24,
    rarity: 5,
    iconColor: "#689F38",
  },
  autumnVegSoup: {
    id: "autumnVegSoup",
    name: "秋收蔬菜汤",
    category: ItemCategory.FOOD,
    description: "多种秋季蔬菜熬制的丰收汤品",
    sellPrice: 190,
    unlockLevel: 20,
    rarity: 4,
    iconColor: "#D97A32",
  },
  gingerVegStew: {
    id: "gingerVegStew",
    name: "姜香蔬菜煲",
    category: ItemCategory.FOOD,
    description: "生姜、大白菜与大蒜炖制的暖香菜煲",
    sellPrice: 200,
    unlockLevel: 21,
    rarity: 4,
    iconColor: "#E6A23C",
  },
  greenEnergyBowl: {
    id: "greenEnergyBowl",
    name: "双绿能量碗",
    category: ItemCategory.FOOD,
    description: "羽衣甘蓝与西兰花搭配的能量蔬菜碗",
    sellPrice: 210,
    unlockLevel: 22,
    rarity: 5,
    iconColor: "#4F8F34",
  },
  garlicWinterRoll: {
    id: "garlicWinterRoll",
    name: "蒜香冬菜卷",
    category: ItemCategory.FOOD,
    description: "大白菜与韭葱制作的蒜香菜卷",
    sellPrice: 220,
    unlockLevel: 23,
    rarity: 5,
    iconColor: "#C9D85A",
  },
  winterRoastPlatter: {
    id: "winterRoastPlatter",
    name: "冬日烤蔬盘",
    category: ItemCategory.FOOD,
    description: "多种冬季根茎与小卷心菜烤制的拼盘",
    sellPrice: 230,
    unlockLevel: 24,
    rarity: 5,
    iconColor: "#8E3F45",
  },

  // ===== 第4类：建筑 (D01-D08) =====
  chickenCoop: {
    id: "chickenCoop",
    name: "鸡舍",
    category: ItemCategory.BUILDING,
    description: "定时生产鸡蛋，自动化生产",
    sellPrice: 100,
    unlockLevel: 6,
    rarity: 4,
    iconColor: "#8B7355",
  },
  barn: {
    id: "barn",
    name: "牛棚",
    category: ItemCategory.BUILDING,
    description: "定时生产牛奶，自动化生产",
    sellPrice: 150,
    unlockLevel: 7,
    rarity: 4,
    iconColor: "#A9A9A9",
  },
  warehouse: {
    id: "warehouse",
    name: "仓库",
    category: ItemCategory.BUILDING,
    description: "牧场生产耗时缩短10%，最多叠加30%",
    sellPrice: 80,
    unlockLevel: 9,
    rarity: 4,
    iconColor: "#8B4513",
  },
  house: {
    id: "house",
    name: "房屋",
    category: ItemCategory.BUILDING,
    description: "每次收获农作物额外获得1经验",
    sellPrice: 90,
    unlockLevel: 11,
    rarity: 3,
    iconColor: "#FF6347",
  },
  well: {
    id: "well",
    name: "井",
    category: ItemCategory.BUILDING,
    description: "定时生产水，高级配方需要",
    sellPrice: 120,
    unlockLevel: 13,
    rarity: 4,
    iconColor: "#87CEEB",
  },
  garden: {
    id: "garden",
    name: "花房",
    category: ItemCategory.BUILDING,
    description: "温暖的室内花房，轮换培育多种鲜花",
    sellPrice: 80,
    unlockLevel: 15,
    rarity: 3,
    iconColor: "#FFB6C1",
  },
  beehive: {
    id: "beehive",
    name: "蜂窝",
    category: ItemCategory.BUILDING,
    description: "定时生产蜂蜜，高价值产品",
    sellPrice: 180,
    unlockLevel: 17,
    rarity: 5,
    iconColor: "#FFD700",
  },

  // ===== 第5类：装饰品 (E01-E10) =====
  sunflower: {
    id: "sunflower",
    name: "向日葵",
    category: ItemCategory.PROCESSED,
    description: "牧场花房培育出的花卉",
    sellPrice: 25,
    unlockLevel: 15,
    rarity: 1,
    iconColor: "#FFD700",
  },
  tulip: {
    id: "tulip",
    name: "郁金香",
    category: ItemCategory.PROCESSED,
    description: "牧场花房培育出的花卉",
    sellPrice: 25,
    unlockLevel: 15,
    rarity: 1,
    iconColor: "#FF1493",
  },
  rose: {
    id: "rose",
    name: "玫瑰",
    category: ItemCategory.PROCESSED,
    description: "牧场花房培育出的花卉",
    sellPrice: 30,
    unlockLevel: 15,
    rarity: 2,
    iconColor: "#DC143C",
  },
  tree: {
    id: "tree",
    name: "树木",
    category: ItemCategory.DECORATION,
    description: "放置后使农作物生长时间缩短1%",
    sellPrice: 40,
    unlockLevel: 6,
    rarity: 2,
    iconColor: "#228B22",
  },
  palmTree: {
    id: "palmTree",
    name: "棕榈树",
    category: ItemCategory.DECORATION,
    description: "放置后使农作物生长时间缩短1%",
    sellPrice: 50,
    unlockLevel: 10,
    rarity: 3,
    iconColor: "#228B22",
  },
  stone: {
    id: "stone",
    name: "石头",
    category: ItemCategory.DECORATION,
    description: "放置后使农作物生长时间缩短1%",
    sellPrice: 20,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#808080",
  },
  log: {
    id: "log",
    name: "木桩",
    category: ItemCategory.DECORATION,
    description: "放置后使农作物生长时间缩短1%",
    sellPrice: 22,
    unlockLevel: 1,
    rarity: 1,
    iconColor: "#8B4513",
  },
  fence: {
    id: "fence",
    name: "木栅栏",
    category: ItemCategory.DECORATION,
    description: "放置后使农作物生长时间缩短1%",
    sellPrice: 28,
    unlockLevel: 4,
    rarity: 2,
    iconColor: "#8B4513",
  },
  tent: {
    id: "tent",
    name: "帐篷",
    category: ItemCategory.DECORATION,
    description: "定时产出合成加速券",
    sellPrice: 60,
    unlockLevel: 14,
    rarity: 3,
    iconColor: "#FFB6C1",
  },
  pumpkinLantern: {
    id: "pumpkinLantern",
    name: "南瓜灯",
    category: ItemCategory.DECORATION,
    description: "放置后使农作物生长时间缩短1%",
    sellPrice: 40,
    unlockLevel: 8,
    rarity: 2,
    iconColor: "#FF8C00",
  },
  flower: {
    id: "flower",
    name: "鲜花",
    category: ItemCategory.PROCESSED,
    description: "牧场花房培育出的基础花卉",
    sellPrice: 18,
    unlockLevel: 15,
    rarity: 2,
    iconColor: "#FFF4C2",
  },

  // ===== 第6类：特殊 (F01-F05) =====
  mysteryBox: {
    id: "mysteryBox",
    name: "神秘礼盒",
    category: ItemCategory.SPECIAL,
    description: "打开可获得随机物品",
    sellPrice: 150,
    unlockLevel: 10,
    rarity: 5,
    iconColor: "#9370DB",
  },
  luckyStar: {
    id: "luckyStar",
    name: "幸运星",
    category: ItemCategory.SPECIAL,
    description: "使用后进行幸运祈愿，随机获得金币或钻石",
    sellPrice: 200,
    unlockLevel: 15,
    rarity: 5,
    iconColor: "#FFD700",
  },
  jade: {
    id: "jade",
    name: "翡翠",
    category: ItemCategory.SPECIAL,
    description: "极稀有矿物，可兑换20钻石",
    sellPrice: 250,
    unlockLevel: 20,
    rarity: 5,
    iconColor: "#00CED1",
  },

  // ===== 第7类：工具 =====
  speedTicket: {
    id: "speedTicket",
    name: "合成加速券",
    category: ItemCategory.TOOL,
    description: "加速合成30秒",
    sellPrice: 0,
    unlockLevel: 4,
    rarity: 3,
    iconColor: "#87CEEB",
  },
  cropSpeedTicket: {
    id: "cropSpeedTicket",
    name: "农作物加速券",
    category: ItemCategory.TOOL,
    description: "使一株生长中的农作物立即成熟",
    sellPrice: 0,
    buyPrice: 100,
    unlockLevel: 4,
    rarity: 3,
    iconColor: "#8BCF4A",
  },
  doubleHarvestCard: {
    id: "doubleHarvestCard",
    name: "双倍收获卡",
    category: ItemCategory.TOOL,
    description: "下次收获数量×2",
    sellPrice: 0,
    unlockLevel: 8,
    rarity: 4,
    iconColor: "#FFD700",
  },
  goldBoostCard: {
    id: "goldBoostCard",
    name: "金币加倍券",
    category: ItemCategory.TOOL,
    description: "下次出售金币×2",
    sellPrice: 0,
    unlockLevel: 12,
    rarity: 4,
    iconColor: "#FFD700",
  },
  universalSeed: {
    id: "universalSeed",
    name: "万能种子",
    category: ItemCategory.TOOL,
    description: "开出1个随机种子",
    sellPrice: 0,
    unlockLevel: 16,
    rarity: 4,
    iconColor: "#FFB6C1",
  },
  makeUpSignInCard: {
    id: "makeUpSignInCard",
    name: "补签卡",
    category: ItemCategory.TOOL,
    description: "补回一次中断的每日签到",
    sellPrice: 0,
    unlockLevel: 1,
    rarity: 3,
    iconColor: "#FF9F91",
  },
  greenhouseCard: {
    id: "greenhouseCard",
    name: "时令温室卡",
    category: ItemCategory.TOOL,
    description: "使一块农田7天内不受季节限制",
    sellPrice: 0,
    unlockLevel: 8,
    rarity: 4,
    iconColor: "#78C89A",
  },
  fourSeasonGreenhouse: {
    id: "fourSeasonGreenhouse",
    name: "恒温温室",
    category: ItemCategory.BUILDING,
    description: "牧场专属跨季种植建筑，初始开放1个花盆",
    sellPrice: 4000,
    buyPrice: 8000,
    unlockLevel: 15,
    rarity: 5,
    iconColor: "#73B985",
  },
};

/** Object.values polyfill (兼容 ES2015 编译目标) */
function objValues<T>(obj: Record<string, T>): T[] {
  const result: T[] = [];
  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) result.push(obj[key]);
  }
  return result;
}

/** 按分类获取物品 */
export function getItemsByCategory(category: ItemCategory): ItemDef[] {
  return objValues(ITEM_DB).filter((i) => i.category === category);
}

/** 获取可种植作物 */
export function getPlantableCrops(): ItemDef[] {
  return objValues(ITEM_DB).filter((i) => i.isCrop);
}

/** 获取物品 */
export function getItem(id: string): ItemDef | undefined {
  return ITEM_DB[id];
}
